version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    privileged: true
    ports:
      - "5000:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - selenium-grid
    links:
      - hub
      - chrome

  app.local:
    build: ./app
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - selenium-grid
  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - selenium-grid
    links:
      - app.local
    ports:
      - 5900:5900

  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

networks:
    selenium-grid:


